#!/usr/bin/env python3
"""Generate docs/RULES.md — the full catalog, one entry per rule.

    python3 scripts/gen_catalog.py            # write docs/RULES.md
    python3 scripts/gen_catalog.py --check    # fail if it is out of date

WHY IT IS GENERATED AND NOT WRITTEN
-----------------------------------
The interesting half of a rule — the symptom a customer actually experiences, the
fix, what it costs — does not live on the Rule object. It lives inside the Finding
the rule yields, because it is written per-occurrence. A hand-maintained catalog
would therefore be a second copy of that text, and the second copy is the one that
goes stale: someone sharpens a symptom line in rules.py, nobody remembers the
markdown, and the public catalog now describes a check the tool no longer performs.

So this runs the auditor against examples/broken-account.json — the fixture that
every rule is required to fire on — and reads the real Finding each rule produced.
If a rule's text changes, this file changes on the next run or CI fails. The
catalog cannot lie about the tool, because it is output of the tool.

A rule that yields no finding on the example is reported as a hole rather than
skipped quietly. That is the same principle the auditor applies to its own
reports: an unrun check is a fact the reader is entitled to.
"""

from __future__ import annotations

import argparse
import os
import sys
from collections import defaultdict

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, ROOT)

from ghlaudit.model import Account  # noqa: E402
from ghlaudit.rules import CATEGORIES, RULES, SEVERITIES, run_all  # noqa: E402

EXAMPLE = os.path.join(ROOT, "examples", "broken-account.json")
OUT = os.path.join(ROOT, "docs", "RULES.md")

CATEGORY_BLURB = {
    "compliance": "What the law and the carriers require of you. These are the "
                  "findings that carry a fine or a blocked number, not just a bad "
                  "experience.",
    "deliverability": "Whether the message physically arrives. A sequence that is "
                      "perfectly written and silently filtered is worth nothing.",
    "routing": "Whether the right person gets the right message at the right time. "
               "The largest category, and the one that produces the messages "
               "customers screenshot and complain about.",
    "hygiene": "Content and maintainability — placeholders, blank merge fields, "
               "references to things that no longer exist. Individually small, "
               "collectively the reason an account becomes unmaintainable.",
    "dead_weight": "Things that exist and do nothing. Not urgent, but every one of "
                   "them is a thing a future maintainer has to read and rule out.",
}

SEVERITY_BLURB = {
    "critical": "the account is texting customers something wrong, right now",
    "high": "it will misfire under normal use, not just at an edge",
    "medium": "it will bite on scale, on handover, or on a bad day",
    "low": "correctness is fine; maintenance or future-proofing is not",
}


def _anchor(rule_id: str) -> str:
    return rule_id.lower()


def build() -> str:
    acct = Account.from_file(EXAMPLE)
    findings, skips = run_all(acct)

    # First finding per rule. Rules fire on several workflows in the example; the
    # text is the same, and the first is as representative as any.
    example_of = {}
    for f in findings:
        example_of.setdefault(f.rule, f)

    by_rule = {r.id: r for r in RULES}
    holes = sorted(set(by_rule) - set(example_of))
    skipped = sorted({s.rule for s in skips})

    grouped = defaultdict(list)
    for r in RULES:
        grouped[r.category].append(r)

    counts = defaultdict(int)
    for r in RULES:
        counts[r.severity] += 1

    out = []
    w = out.append

    w("# The rule catalog")
    w("")
    w(f"**{len(RULES)} checks.** Every one encodes a failure that has actually shipped "
      f"in a live GoHighLevel account — not a style opinion. Each entry below states "
      f"the symptom in the words a business owner would use, because that is who reads "
      f"the report.")
    w("")
    w("> This page is generated by `scripts/gen_catalog.py` from a real run against "
      "`examples/broken-account.json`, the fixture every rule is required to fire on. "
      "The symptom and fix text below is the exact text the tool emits. It cannot "
      "drift from the code, because it is output of the code.")
    w("")

    w("## Severity")
    w("")
    w("| Severity | Count | Means |")
    w("|---|---:|---|")
    for sev in SEVERITIES:
        w(f"| **{sev}** | {counts[sev]} | {SEVERITY_BLURB[sev]} |")
    w("")

    w("## Categories")
    w("")
    w("The health score is graded on these five axes, so a category with no findings "
      "is a category the account is genuinely clean on.")
    w("")
    w("| Category | Checks | What it covers |")
    w("|---|---:|---|")
    for cat in CATEGORIES:
        w(f"| [{cat}](#{cat.replace('_', '-')}) | {len(grouped[cat])} | "
          f"{CATEGORY_BLURB[cat]} |")
    w("")

    w("## Index")
    w("")
    w("| ID | Severity | Check |")
    w("|---|---|---|")
    for r in sorted(RULES, key=lambda r: r.id):
        w(f"| [{r.id}](#{_anchor(r.id)}) | {r.severity} | {r.title} |")
    w("")

    for cat in CATEGORIES:
        rules = sorted(grouped[cat], key=lambda r: (SEVERITIES.index(r.severity), r.id))
        if not rules:
            continue
        w("---")
        w("")
        w(f"## {cat}")
        w("")
        w(CATEGORY_BLURB[cat])
        w("")
        for r in rules:
            f = example_of.get(r.id)
            w(f"### {r.id}")
            w("")
            w(f"**{r.title}** — `{r.severity}`"
              + (f" · tags: {', '.join(f'`{t}`' for t in r.tags)}" if r.tags else ""))
            w("")
            if f is None:
                w("> ⚠️ This check did not fire on the example account, so no sample "
                  "output could be generated for it. That is a gap in the fixture, "
                  "not a passing grade — see the holes section at the end.")
                w("")
                continue
            w(f"*What it looks like:* {f.symptom}")
            w("")
            w(f"*The fix:* {f.fix}")
            w("")
            if f.cost:
                w(f"*What it costs:* {f.cost}")
                w("")

    w("---")
    w("")
    w("## Coverage of this page")
    w("")
    w(f"- Rules in the catalog: **{len(RULES)}**")
    w(f"- Rules with sample output above: **{len(example_of)}**")
    if holes:
        w(f"- ⚠️ Rules that did not fire on the example: "
          f"{', '.join(holes)} — the fixture needs a case for these.")
    else:
        w("- Rules that did not fire on the example: **none**. Every check in the "
          "catalog is demonstrated by the shipped fixture.")
    if skipped:
        w(f"- ⚠️ Checks that skipped for want of account context: {', '.join(skipped)}")
    else:
        w("- Checks that skipped for want of account context: **none**.")
    w("")
    return "\n".join(out) + "\n"


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if docs/RULES.md is out of date")
    args = ap.parse_args(argv)

    text = build()
    if args.check:
        current = open(OUT).read() if os.path.exists(OUT) else ""
        if current != text:
            print("docs/RULES.md is STALE — run python3 scripts/gen_catalog.py",
                  file=sys.stderr)
            return 1
        print("docs/RULES.md is current")
        return 0

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as fh:
        fh.write(text)
    print(f"wrote docs/RULES.md — {len(RULES)} rules")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
